#!/bin/sh
set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

echo "[Auth-inspector] Configuring package..."

if systemctl list-unit-files | grep -q "^auth-inspector.service"; then
    echo "[Auth-inspector] Włączanie autostartu i uruchamianie usługi..."
	systemctl daemon-reload
    systemctl enable auth-inspector.service
    systemctl restart auth-inspector.service
else
    echo "[Auth-inspector] Warning: Couldn't find auth-inspector.service in the filesystem."
    echo "                 Please make sure that the systemd.service file was properly implemented."
fi

exit 0