#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -d /run/systemd/system ] && systemctl list-unit-files | grep -q "^auth-inspector.service"; then
        echo "[Auth-inspector] Turning of the auth-inspector service..."
        systemctl stop auth-inspector.service || true
        systemctl disable auth-inspector.service || true
        systemctl daemon-reload || true
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -d "/var/log/auth-inspector" ]; then
        echo "[Auth-inspector] Removing the package files..."
        echo "[Auth-inspector] Deleting the log directory /var/log/auth-inspector..."
        rm -rf /var/log/auth-inspector
    fi
fi

exit 0