name: Python Unit Tests

# <-- Kiedy automatyzacja ma się uruchomić
on:
  push:
    branches: [ "main" ]  # <-- Uruchom przy każdym wypchnięciu kodu na gałąź main
  pull_request:
    branches: [ "main" ]  # <-- Uruchom przy próbie połączenia kodu z main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    # I. Pobierz pliki z Twojego repozytorium do wirtualnej maszyny
    - name: Checkout repository code
      uses: actions/checkout@v4

    # II. Instalacja zależności systemowych i Pythona
    - name: Install systemd development libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libsystemd-dev python3-systemd

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # III. Instalacja bilbiotek z PIP
    - name: Install Python requirements
      run: |
        python -m pip install --upgrade pip
        pip install systemd-python
        pip install bandit

    # IV. Uruchomienie testów jednostkowych
    - name: Run unit tests
      run: |
        python -m unittest test_auth_inspector.py

    # V. Uruchomienie testów bezpieczeństwa
    - name: Run securiy scan
      run: |
        bandit -c pyproject.toml -r . -l
